// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarrySprouts.Data;

#nullable disable

namespace StarrySprouts.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220610221103_AddingValidations")]
    partial class AddingValidations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StarrySprouts.Models.CategoryModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Beautiful fantasy-inspired stickers for any occasion!",
                            CategoryName = "Stickers"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Cute and snuggly creations to physically be with you!",
                            CategoryName = "Plushy"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "Fantasy-inspired apparel to represent the StarrySprouts brand!",
                            CategoryName = "Apparel"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDescription = "An assortment of goodies from StarrySprouts!",
                            CategoryName = "Misc"
                        });
                });

            modelBuilder.Entity("StarrySprouts.Models.OrderDetailsModel", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("StarrySprouts.Models.OrderModel", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("StarrySprouts.Models.ProductModel", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ImageThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Though many dragons may be fearsome, there are some that also enjoy the soft beauty of flowers. The floral scents calm them so, and the brilliant colours of the petals are the equivalent of treasure for them. When the flowers bloom, there surely will be dragons nearby. A perfect fairy-tale touch to flourish any surface!",
                            ImageThumbnailUrl = "/assets/images/FloralDragon/FloralDragonStickerSheetThumbnail.jpg",
                            ImageUrl = "/assets/images/FloralDragon/FloralDragonStickerSheet.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Floral Dragon Sticker Sheet",
                            Price = 4.90m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Occasionally fluttering by is the sweet fairy penguins. They much prefer to swim and their wings are waterproof, which fortunately helps to catch their favourite snack: fish! Any kind of fish can tame these docile creatures.",
                            ImageThumbnailUrl = "/assets/images/FairyPenguin/FairyPenguinStickerSheetThumbnail.jpg",
                            ImageUrl = "/assets/images/FairyPenguin/FairyPenguinStickerSheet.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Fairy Penguin Sticker Sheet",
                            Price = 4.90m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Out in space, there lives the moon rabbits. Harvesters of stars and growers of space carrots! There's a bustling colony of them that live on the moon, and they love coming down to the lands of Sprout to go on vacation. Many businesses of Sprout hire moon rabbits to go and explore the vastness of space to bring back rare minerals and materials. At the end of the day, a moon rabbit loves to cozy up and watch a good meteor shower.",
                            ImageThumbnailUrl = "/assets/images/MoonBunny/MoonBunnyStickerSheetThumbnail.jpg",
                            ImageUrl = "/assets/images/MoonBunny/MoonBunnyStickerSheet.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Moon Bunny Sticker Sheet",
                            Price = 4.90m
                        });
                });

            modelBuilder.Entity("StarrySprouts.Models.ShoppingCartItemsModel", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartItemId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("StarrySprouts.Models.OrderDetailsModel", b =>
                {
                    b.HasOne("StarrySprouts.Models.OrderModel", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarrySprouts.Models.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StarrySprouts.Models.ProductModel", b =>
                {
                    b.HasOne("StarrySprouts.Models.CategoryModel", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StarrySprouts.Models.ShoppingCartItemsModel", b =>
                {
                    b.HasOne("StarrySprouts.Models.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StarrySprouts.Models.CategoryModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StarrySprouts.Models.OrderModel", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
